name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

  frontend-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Frontend Dependencies
      working-directory: ./matchify-frontend
      run: npm install

    - name: Start Frontend Server
      working-directory: ./matchify-frontend
      run: npm start &

    - name: Wait for Frontend Server to be Ready
      run: sleep 15  # Adjust the wait time as necessary for your server to start

    - name: Run Frontend Tests
      working-directory: ./matchify-frontend
      run: npm test

    - name: Upload Frontend Test Report
      uses: actions/upload-artifact@v3
      with:
        name: frontend-test-report
        path: ./matchify-frontend/features/reports/

  backend-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Backend Dependencies
      working-directory: ./matchify-backend
      run: npm install

    - name: Run Backend Tests
      working-directory: ./matchify-backend
      run: npm test

    - name: Upload Backend Test Report
      uses: actions/upload-artifact@v3
      with:
        name: backend-test-report
        path: ./matchify-backend/jest-reports/
